---
- import_playbook: zfs.yml
- import_playbook: consul.yml
- import_playbook: grafana.yml
- import_playbook: grafana_auto_annotations.yml
- import_playbook: systemd_dropins.yml
- import_playbook: loki.yml
- import_playbook: etcd.yml
- import_playbook: memcached.yml
- import_playbook: lb.yml
- import_playbook: patroni_server.yml
- import_playbook: distributed-timescaledb.yml
- import_playbook: postgresql_client.yml
- import_playbook: victoriametrics.yml
- import_playbook: promscale.yml
- import_playbook: cortex.yml
- import_playbook: proxy_exporter.yml
- import_playbook: prometheus.yml
- import_playbook: m3db.yml
