---
node_exporter_version: 1.1.2
node_exporter_enabled_collectors:
  - drbd
  - interrupts
  - ksmd
  - logind
  - meminfo_numa
  - mountstats
  - network_route
  - ntp
  - processes
  - qdisc
  - systemd
  - tcpstat
node_exporter_web_max_requests: 0
